name: Creating and Deploying a VM on Azure on Github Actions

env:
    OUTPUT_PATH: ${{ github.workspace }}

on: [push]

jobs:

# Deploy a VM in Azure

  DeployVM:

    runs-on: windows-latest

    steps:

    # checkout code from repo

    - name: repo checkout
      uses: actions/checkout@v1

    - name: look for VM creation ps1 file
      run: |
        ls '${{ env.OUTPUT_PATH}}\getVMFiles\createVMActionFile.ps1
    
    - name: Create virtual machine in Azure

      env:

           RESOURCE_GROUP: rg-serverless-artillery-run-ec
           RESOURCE_GROUP_REGION: westus
           SERVER_NAME: githubactions
           ADMIN_LOGIN: nsc-ad-440-user
        
      run: >

            powershell -command "& '${{ env.OUTPUT_PATH}}\getVMFIles\createVMActionFile.ps1'"
            -servicePrincipal ${{ secrets.SERVICE_PRINCIPAL_APPID }}
            -servicePrincipalSecret ${{ secrets.SERVICE_PRINCIPAL_SECRET }}
            -servicePrincipalTenantId ${{ secrets.SERVICE_PRINCIPAL_TENANTID }}
            -azureSubscriptionName ${{ secrets.AZURE_SUBSCRIPTION_ID}}
            -resourceGroupName %RESOURCE_GROUP%
            -resourceGroupNameRegion %RESOURCE_GROUP_REGION%
            -adminLogin %ADMIN_LOGIN%
            -adminPassword ${{ secrets.ADMIN_PASSWORD }}
